baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'serenity'

[menu]
[[menu.main]]
name = "Pricing"
url = "/pricing"
weight = 1
[[menu.main]]
name = "Company"
url = "/company"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.main]]
name = "Login"
url = "/login"
weight = 4

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'
