description = "Radiant helps you sell more by revealing sensitive information about your customers."

[announcement]
# text = "Radiant raises $100M Series A from Tailwind Ventures"
# link = "/blog/radiant-raises-100m-series-a-from-tailwind-ventures"

# Homepage Content
[hero]
title = "Professional Home Security with Complete Privacy"
description = "High-end surveillance systems that keep your data on your property, not in the cloud"

[[hero.buttons]]
text = "Get started"
url = "#"
class = "inline-flex items-center justify-center px-4 py-[calc(--spacing(2)-1px)] rounded-full border border-transparent bg-gray-950 dark:bg-gray-100 shadow-md text-base font-medium whitespace-nowrap text-white dark:text-black data-disabled:bg-gray-950 data-disabled:opacity-40 data-hover:bg-gray-800"

[[hero.buttons]]
text = "Learn more"
url = "/pricing"
class = "relative inline-flex items-center justify-center px-4 py-[calc(--spacing(2)-1px)] rounded-full border border-transparent bg-white/15 ring-1 shadow-md ring-[#D15052]/15 after:absolute after:inset-0 after:rounded-full after:shadow-[inset_0_0_2px_1px_#ffffff4d] text-base font-medium whitespace-nowrap text-gray-950 dark:text-gray-50 data-disabled:bg-white/15 data-disabled:opacity-40 data-hover:bg-white/20"

[feature_section]
tag = "Privacy-First Security"
title = "Security Without Big Tech"
description = "Keep your home secure while keeping big tech companies out of your personal life. We install professional-grade security systems that store all footage right in your home - never in someone else's cloud."
image = "/images/security-dashboard.png"

[[feature_section.features]]
title = "Complete Data Privacy."
description = "Your security footage stays in your home, on your hardware. No cloud storage, no external streaming, no compromises. What happens on your property stays on your property."
icon = """
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="absolute top-1 left-1 size-5 text-sky-600">
  <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.451 10.451 0 0 1 12 4.5c4.756 0 8.773 3.162 10.065 7.498a10.522 10.522 0 0 1-4.293 5.774M6.228 6.228 3 3m3.228 3.228 3.65 3.65m7.894 7.894L21 21m-3.228-3.228-3.65-3.65m0 0a3 3 0 1 0-4.243-4.243m4.242 4.242L9.88 9.88" />
</svg>
"""

[[feature_section.features]]
title = "Professional Installation."
description = "Expert installation of high-quality cameras, sensors, and networking equipment, configured for optimal coverage and reliability. We handle the technical details so you don't have to."
icon = """
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="absolute top-1 left-1 size-5 text-sky-600">
  <path stroke-linecap="round" stroke-linejoin="round" d="M11.42 15.17 17.25 21A2.652 2.652 0 0 0 21 17.25l-5.877-5.877M11.42 15.17l2.496-3.03c.317-.384.74-.626 1.208-.766M11.42 15.17l-4.655 5.653a2.548 2.548 0 1 1-3.586-3.586l6.837-5.63m5.108-.233c.55-.164 1.163-.188 1.743-.14a4.5 4.5 0 0 0 4.486-6.336l-3.276 3.277a3.004 3.004 0 0 1-2.25-2.25l3.276-3.276a4.5 4.5 0 0 0-6.336 4.486c.091 1.076-.071 2.264-.904 2.95l-.102.085m-1.745 1.437L5.909 7.5H4.5L2.25 3.75l1.5-1.5L7.5 4.5v1.409l4.26 4.26m-1.745 1.437 1.745-1.437m6.615 8.206L15.75 15.75M4.867 19.125h.008v.008h-.008v-.008Z" />
</svg>

"""

[[feature_section.features]]
title = "Local Control."
description = "Your security system runs on a dedicated local network, accessible only through your private infrastructure. You own and control everything - no subscriptions, no cloud dependence, no external oversight."
icon = """
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="absolute top-1 left-1 size-5 text-sky-600">
  <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
</svg>

"""

[footer]
[footer.cta]
eyebrow = "Protect Your Privacy"
title = "Ready to take control of your security?<br>Schedule a free consultation."
description = "No obligation, no pressure - just straightforward advice about keeping your data truly private."

[footer.cta.button]
text = "Book Free Consultation"
url = "#"

[[footer.columns]]
title = "Product"
[[footer.columns.links]]
text = "Pricing"
url = "/pricing"
[[footer.columns.links]]
text = "Analysis"
url = "#"
[[footer.columns.links]]
text = "API"
url = "#"

[[footer.columns]]
title = "Company"
[[footer.columns.links]]
text = "Careers"
url = "#"
[[footer.columns.links]]
text = "Blog"
url = "/blog"
[[footer.columns.links]]
text = "Company"
url = "/company"

[[footer.columns]]
title = "Support"
[[footer.columns.links]]
text = "Help center"
url = "#"
[[footer.columns.links]]
text = "Community"
url = "#"

[[footer.social]]
name = "Facebook"
url = "https://facebook.com"
icon = '''<svg viewBox="0 0 16 16" fill="currentColor" class="size-4">
      <path fill-rule="evenodd" d="M16 8.05C16 3.603 12.418 0 8 0S0 3.604 0 8.05c0 4.016 2.926 7.346 6.75 7.95v-5.624H4.718V8.05H6.75V6.276c0-2.017 1.194-3.131 3.022-3.131.875 0 1.79.157 1.79.157v1.98h-1.008c-.994 0-1.304.62-1.304 1.257v1.51h2.219l-.355 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.95z"/>
    </svg>'''

[[footer.social]]
name = "X"
url = "https://x.com"
icon = '''<svg viewBox="0 0 16 16" fill="currentColor" class="size-4">
      <path d="M12.6 0h2.454l-5.36 6.778L16 16h-4.937l-3.867-5.594L2.771 16H.316l5.733-7.25L0 0h5.063l3.495 5.114L12.6 0zm-.86 14.376h1.36L4.323 1.539H2.865l8.875 12.837z"/>
    </svg>'''

[[footer.social]]
name = "LinkedIn"
url = "https://linkedin.com"
icon = '''<svg viewBox="0 0 16 16" fill="currentColor" class="size-4">
      <path d="M14.82 0H1.18A1.169 1.169 0 000 1.154v13.694A1.168 1.168 0 001.18 16h13.64A1.17 1.17 0 0016 14.845V1.15A1.171 1.171 0 0014.82 0zM4.744 13.64H2.369V5.996h2.375v7.644zm-1.18-8.684a1.377 1.377 0 11.52-.106 1.377 1.377 0 01-.527.103l.007.003zm10.075 8.683h-2.375V9.921c0-.885-.015-2.025-1.234-2.025-1.218 0-1.425.966-1.425 1.968v3.775H6.233V5.997H8.51v1.05h.032c.317-.601 1.09-1.235 2.246-1.235 2.405-.005 2.851 1.578 2.851 3.63v4.197z"/>
    </svg>'''